[package]
name = "turtleactivitypub"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.147", features = ["derive"]  }
serde_json = "1.0"
chrono = { version = "0.4.22", features = ["serde"] }
reqwest = { version = "0.11.12", features = ["blocking"] }